services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - pokemon-network
    volumes:
      - .:/app
      - /app/node_modules
networks:
  pokemon-network:
    external: true