services:
  nginx:
    image: nginx:1.26.2-alpine
    env_file:
      - .env
    ports:
      - "${HOST_HTTP_PORT}:80"
      - "${HOST_HTTPS_PORT}:443"
    networks:
      - pokemon-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  pokemon-network:
    external: true
