services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - pokemon-network
    env_file:
      - .env
    command: ["python", "-u", "main.py"]

networks:
  pokemon-network:
    external: true
